fix: honor explicit prefix
npm/arborist pull request #254
Opened 2021-03-17 06:17 UTC by jameschensmith

**Summary**

Honors explicit prefix. npm-package-arg was being used incorrectly in reify when saving the ideal tree. Only the spec was being passed in, which resulted in some unusual results (submitted a ticket to address that in npm-package-arg as well).

Once this was addressed, another issue was spotted, where passing no version on a new package results in `*` being added. This now resolves correctly to a range (previously, it resolved to a tag). When resolving `range` shortly after, though, `*` is resolved instead of `prefixRange` due to the existing checks (which were/are completely valid). Adds an additional check for range to address having `prefixRange` resolved instead of `*` in `package.json` (`*` should still resolve if `child.version` is falsy).

In addition, there was a test which had an unusual alias. This fix brought that abnormality to light. This request corrects that test.

## References

Fixes #253.

2021-03-17 06:31 UTC, jameschensmith commented on lib/arborist/reify.js
> +          const range = !isRange || subset(prefixRange, spec, { loose: true }) || spec === '*'
If this is the route to go, thoughts on switching these checks for speed?

```suggestion
          const range = !isRange || spec === '*' || subset(prefixRange, spec, { loose: true })
```

2021-03-18 01:57 UTC, jameschensmith commented
Before merging this PR, I would love for the subset fix to be resolved. I created an issue for it (npm/node-semver#374), and will be submitting a PR shortly.

2021-03-22 17:57 UTC, isaacs commented on test/arborist/reify.js
> -        d: 'd@npm:c@1.x <1.9.9',
Yeah, this looks weird.  Probably shouldn't end up with the name in there...

2021-03-22 18:06 UTC, isaacs requested changes
So, I don't think this is quite the right way to go.  I might be wrong, and I agree that there is a bug here, but it'd be much easier to evaluate if we start from a failing test (such as the case you suggested), and then figure out exactly where it's going wrong and how to make that test pass.

I'll dig in today and try to get more insight.  At the very least, saving the name on the right-hand-side of the `dependencies` field is definitely a bug, that shouldn't be happening.

2021-03-23 01:44 UTC, isaacs commented
Ah, ok, the `|| spec === '*'` part is unnecessary, but now that npm/node-semver#377 has shipped, I think the other bit looks correct.

This patch seems like it fixes the problem, and is pretty close to what you put here.  Want to take a look? https://gist.github.com/isaacs/7d42bb2672905d3b27e70bc4015ca135

2021-03-23 01:56 UTC, jameschensmith commented
> Ah, ok, the `|| spec === '*'` part is unnecessary, but now that [npm/node-semver#377](https://github.com/npm/node-semver/pull/377) has shipped, I think the other bit looks correct.
> 
> This patch seems like it fixes the problem, and is pretty close to what you put here. Want to take a look? [gist.github.com/isaacs/7d42bb2672905d3b27e70bc4015ca135](https://gist.github.com/isaacs/7d42bb2672905d3b27e70bc4015ca135)

Yes! That's what I was planning to do after the patch in node-semver. :grin::clap: If you want me to finish the PR up, let me know. Otherwise, let's get this patched! :raised_hands:

2021-03-23 03:07 UTC, jameschensmith commented
Went ahead and addressed the requested changes. Very straightforward :blush: Thanks for your reviews today!

2021-03-23 16:06 UTC, closed without merging

2021-03-23 16:19 UTC, isaacs commented
This is shipped now!  Will be in next npm release.  I shuffled around the commit history a bit so that semver update is in one, and the functional updates come together after it.  Thanks!