fix(reify): do not clean up omitted nodes with no parent
npm/arborist pull request #277
Opened 2021-05-05 21:28 UTC by wraithgar

Co-authored by @nlf

When reify goes to add omits to the trash list, sometimes it adds things
it shouldn't, such as top level nodes that are actually links, but
they're only links elsewhere in the tree where they are properly placed
(i.e. with the root as the parent).

This PR prevents things like "npm install --production" deleting the
contents of a linked dev dependency

## References
Closes https://github.com/npm/cli/issues/2889

2021-05-05 21:28 UTC, wraithgar commented
Still needs a test to prevent regression on the bug it's fixing.

2021-05-06 14:52 UTC, darcyclarke requested changes
Waiting on test coverage

2021-05-06 15:21 UTC, isaacs commented
Here's a test:

```patch
diff --git a/test/arborist/reify.js b/test/arborist/reify.js
index e3f9f19a..f58aa90c 100644
--- a/test/arborist/reify.js
+++ b/test/arborist/reify.js
@@ -1691,3 +1691,52 @@ console.log('ok 1 - this is fine')
     stdio: 'pipe',
   }), 'test result')
 })
+
+t.test('do not delete linked targets when link omitted', async t => {
+  const path = t.testdir({
+    'package.json': JSON.stringify({
+      devDependencies: {
+        foo: 'file:foo',
+      },
+      dependencies: {
+        abbrev: '',
+      },
+    }),
+    node_modules: {
+      foo: t.fixture('symlink', '../foo'),
+      abbrev: {
+        'package.json': JSON.stringify({
+          name: 'abbrev',
+          version: '1.2.3',
+        }),
+      },
+    },
+    foo: {
+      'package.json': JSON.stringify({
+        name: 'foo',
+        version: '1.2.3',
+        dependencies: {
+          bar: '1.2.3',
+        },
+      }),
+      'index.js': 'console.log("hello from foo")',
+      node_modules: {
+        bar: {
+          'package.json': JSON.stringify({
+            name: 'bar',
+            version: '1.2.3',
+          }),
+        },
+      },
+    },
+  })
+  const barpj = resolve(path, 'foo/node_modules/bar/package.json')
+  const fooindex = resolve(path, 'foo/index.js')
+  t.equal(fs.existsSync(barpj), true, 'bar package.json present')
+  t.equal(fs.existsSync(fooindex), true, 'foo index.js present')
+  const tree = await reify(path, { omit: ['dev'] })
+  t.equal(fs.existsSync(barpj), true, 'bar package.json still present')
+  t.equal(fs.existsSync(fooindex), true, 'foo index.js still present')
+  t.notOk(tree.children.get('foo'), 'does not have foo child any more')
+  t.equal(tree.fsChildren.size, 1, 'still has foo fschild')
+})

```

It looks like it's still deleting the _children_ of those linked targets.

2021-05-06 15:24 UTC, isaacs requested changes
Should check that it's a descendant of the idealTree, rather than just that it's a top node.

Test:

```patch
diff --git a/lib/arborist/reify.js b/lib/arborist/reify.js
index 67bd2fd3..e62017f9 100644
--- a/lib/arborist/reify.js
+++ b/lib/arborist/reify.js
@@ -406,10 +406,11 @@ module.exports = cls => class Reifier extends cls {
       return
 
     process.emit('time', 'reify:trashOmits')
-    // node.parent is checked to make sure this is a node that's in the tree, and
-    // not the parent-less top level nodes
+    // Only trash nodes that are in the idealTree's node_modules
+    // folder, ie are descendants of the idealTree.  Anything outside
+    // should be left alone.
     const filter = node =>
-      node.parent &&
+      node.isDescendantOf(this.idealTree) &&
         (node.peer && this[_omitPeer] ||
           node.dev && this[_omitDev] ||
           node.optional && this[_omitOptional] ||
diff --git a/test/arborist/reify.js b/test/arborist/reify.js
index e3f9f19a..f58aa90c 100644
--- a/test/arborist/reify.js
+++ b/test/arborist/reify.js
@@ -1691,3 +1691,52 @@ console.log('ok 1 - this is fine')
     stdio: 'pipe',
   }), 'test result')
 })
+
+t.test('do not delete linked targets when link omitted', async t => {
+  const path = t.testdir({
+    'package.json': JSON.stringify({
+      devDependencies: {
+        foo: 'file:foo',
+      },
+      dependencies: {
+        abbrev: '',
+      },
+    }),
+    node_modules: {
+      foo: t.fixture('symlink', '../foo'),
+      abbrev: {
+        'package.json': JSON.stringify({
+          name: 'abbrev',
+          version: '1.2.3',
+        }),
+      },
+    },
+    foo: {
+      'package.json': JSON.stringify({
+        name: 'foo',
+        version: '1.2.3',
+        dependencies: {
+          bar: '1.2.3',
+        },
+      }),
+      'index.js': 'console.log("hello from foo")',
+      node_modules: {
+        bar: {
+          'package.json': JSON.stringify({
+            name: 'bar',
+            version: '1.2.3',
+          }),
+        },
+      },
+    },
+  })
+  const barpj = resolve(path, 'foo/node_modules/bar/package.json')
+  const fooindex = resolve(path, 'foo/index.js')
+  t.equal(fs.existsSync(barpj), true, 'bar package.json present')
+  t.equal(fs.existsSync(fooindex), true, 'foo index.js present')
+  const tree = await reify(path, { omit: ['dev'] })
+  t.equal(fs.existsSync(barpj), true, 'bar package.json still present')
+  t.equal(fs.existsSync(fooindex), true, 'foo index.js still present')
+  t.notOk(tree.children.get('foo'), 'does not have foo child any more')
+  t.equal(tree.fsChildren.size, 1, 'still has foo fschild')
+})

```

2021-05-06 15:24 UTC, isaacs commented on lib/arborist/reify.js
> +      node.parent &&
```suggestion
      node.isDescendantOf(this.idealTree) &&
```

2021-05-06 16:58 UTC, nlf approved these changes

2021-05-06 16:59 UTC, nlf approved these changes
changes applied and test fixed :+1:

2021-05-06 17:08 UTC, merged