feat(links): add lifecycle scripts interdependency
npm/arborist pull request #303
Opened 2021-07-14 21:00 UTC by ruyadorno

Adds the ability for lifecycle scripts of Link nodes to depend
on each other, such that a `prepare` script of linked module **A**
can make use of files that are a result of a `prepare` script of
a linked package **B**.

This is important in order to unlock workflows in which a workspace
needs to make use of another workspace but they all have transpilation
steps (very common in Typescript projects) so tracking the order
(and completion) in which the dependencies lifecycle scripts runs
becomes necessary.

## References
Fixes: https://github.com/npm/cli/issues/3034

2021-07-22 20:22 UTC, isaacs requested changes
This encounters a deadlock when there is a cycle between link dependencies.  Example to reproduce it:

```patch
diff --git a/test/arborist/rebuild.js b/test/arborist/rebuild.js
index 77c38623..53993201 100644
--- a/test/arborist/rebuild.js
+++ b/test/arborist/rebuild.js
@@ -790,6 +790,7 @@ t.test('scripts dependencies between Link nodes', async t => {
             // at least 20ms prior to writing that file
             prepare: "node -e \"setTimeout(() => { require('fs').writeFileSync(require('path').resolve('index.js'), 'module.exports = function HELLO() {}.name;') }, 20)\"",
           },
+          dependencies: { b: '' },
         }),
       },
       d: {
```

The need is clearly valid, but we have to be able to determine the case where a dependency is waiting on something that exists in a cycle.  Also, I think we can probably address it without needing a class to manage references and polling?  At the very least, the Script class here needs to be a standalone thing with unit tests.

2021-07-29 11:25 UTC, felschr commented
We hit this issue afer updating to npm@7.20 and `npm install` suddenly failing because it tries to run `prepare` scripts out of order. I'm happy to see there's already a PR in the pipeline.
With all the other recent additions npm workspaces are starting to become really useful, great work!

2021-08-12 21:07 UTC, alvis commented
Maybe what we need is a mechanism to detect a cyclic dependency and raise a warning?

Since 7.20, we can't use workspace with lerna anymore since npm would try to run `prepare` before `leana bootstrap`.
Besides the out-of-order `prepare` sequence, what make it worser is that `npm i --ignore-scripts` doesn't even stop `npm` from running the `prepare` scripts.

2022-01-18 22:58 UTC, fritzy commented
@ruyadorno Closing this in order to archive the repo.

2022-01-18 22:58 UTC, closed without merging